import 'package:flutter/material.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'services/api_service.dart';
import 'services/fcm_service.dart';
import 'firebase_options.dart'; // Will be generated by user via flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDateFormatting();

  try {
    // Note: You need to run `flutterfire configure` to generate firebase_options.dart
    // or provide google-services.json / GoogleService-Info.plist manually.
    // Assuming firebase_options.dart exists or DefaultFirebaseOptions are available.
    // If not, use standard init.
    await Firebase.initializeApp(
       options: DefaultFirebaseOptions.currentPlatform,
    );
    await FcmService.initialize();
  } catch (e) {
    debugPrint("Firebase init failed (expected if not configured): $e");
  }

  final token = await ApiService.getToken();
  runApp(MyApp(isLoggedIn: token != null));
}

class MyApp extends StatelessWidget {
  final bool isLoggedIn;
  const MyApp({super.key, required this.isLoggedIn});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ZZZ',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: isLoggedIn ? const HomeScreen() : const LoginScreen(),
    );
  }
}
